image:
  file: .gitpod/Dockerfile
tasks:
  - init: |
      flutter doctor
      flutter pub get

ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: ignore
  - port: 5037
    onOpen: ignore
  - port: 9100
    onOpen: ignore
  - port: 8080
    visibility: public
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - editorconfig.editorconfig
