image:
  file: .gitpod.Dockerfile
tasks:
  # flutter run --web-port 8080
  - init: |
      flutter upgrade
      flutter config --enable-web
      flutter doctor
      flutter pub get

ports:
  - port: 5900
    onOpen: ignore
    # vnc
  - port: 6080
    onOpen: ignore

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
    - editorconfig.editorconfig
